EMentors/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main/index'
  root 'main#index'
  get 'students/dashboard/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  
  scope module: :teacher do
    resources :courses do
      resources :topics
    end
    resources :subscribers
  end
  
  scope module: :student do
    resources :dashboard 
    resources :purchases
    resources :subscriptions
    post "/checkout/create", to: "checkout#create"
    get '/checkout/success', to: "checkout#success"
    get '/checkout/cancel', to: "checkout#cancel"
    get 'payment/payment_successful', to: "payments#payment_successful"
    get 'payment/payment_cancel', to: "payments#payment_cancel"
  end
end

EMentors/app/controllers/student/base_controller.rb
module Student
    class BaseController < ::ApplicationController
        before_action :authenticate_user!, :is_student?
        layout 'student'
    end
end

EMentors/app/controllers/student/checkout_controller.rb
module Student
    class CheckoutController < ::ApplicationController
        before_action :set_course_and_user_for_payment, only: [:create]
        before_action :set_payment, only: %i[success cancel]
        
        def create
            @session = CheckoutCreator.new(current_user, @course, checkout_success_url, checkout_cancel_url, @payment).call

            respond_to do |format|
                format.js
            end
        end

        def success
            session_id = params[:session_id]
            expand = ["line_items"]
            session_with_expand = CheckoutRetrieve.new(session_id, expand, @payment).call
            # byebug
            @course_name = session_with_expand.line_items.data[0].description
            @course = Course.find_by(course_name: @course_name)
        end
        
        def cancel
            @payment.cancel!
        end

        private

        def set_course_and_user_for_payment
            @course = Course.find(params[:id])
            @payment = @course.payments.new(user_id: current_user.id) 
            @payment.save
        end

        def set_payment
            @payment = Payment.find_by(id: params[:payment_id])
        end

        # def ask_refund
        #     Stripe::Refund.create({
        #         payment_intent: ,
        #     })
        # end
    end    
end    

EMentors/app/controllers/student/dashboard_controller.rb
module Student
    class DashboardController < BaseController
        before_action :course_id_valid?, only: [:show]
        def index
            @courses = Course.where.not(id: current_user.purchases.pluck(:course_id)).kept
        end

        def show;end
        
        private
        
        def course_id_valid?
            @course = Course.find_by(id: params[:id])
            if @course.nil?
                redirect_to (request.env["HTTP REFERER"] || dashboard_index_path), alert: "Error finding course"
            else 
                @course
            end
        end
    end
end

EMentors/app/controllers/student/subscriptions_controller.rb
module Student
    class SubscriptionsController < BaseController
        before_action :check_subscriber?, only: [:show]
        def index
            @courses = Course.where(id: current_user.purchases.pluck(:course_id))
        end

        private
        
        def check_subscriber?
            @course = Course.find_by(id: params[:id])
            
            if @course.present? && @course.purchases.pluck(:user_id).include?(current_user.id)
                @course
            else 
                redirect_to (request.env["HTTP_REFERER"] || subscriptions_path), alert:"You are unauthorised for this!"
            end 
        end
    end
end

EMentors/app/views/student/dashboard/index.html.erb
<div class="d-flex align-items-center justify-content-center" >
    <h1>Hello <%= current_user.first_name %>, Welcome to EMentors</h1>
</div>
<ul>
<div class="row row-cols-1 row-cols-md-3 g-4" >
<% @courses.each do |course|%>
    <div class="col" style="width: 25%;">
    <div class="card" style="min-height: 100%;">
     <div class="card-body" style="background-color: #66A5AD  ; color: #c4dfe6;">
     <div ><h5 class="d-flex align-items-center justify-content-center card-title" style="color: #003b46;"><%= course.course_name %> </h5></div>
     <p class="card-text">
        <strong style="color: #003b46;">Description: </strong><%= course.course_description %> <br>
        <strong style="color: #003b46;">Duration: </strong><%= course.course_duration %><br>
        <strong style="color: #003b46;">Price: </strong><strong>Rs.</strong><%= course.course_price %><br>
        <strong style="color: #003b46;">Instructor: </strong><%= course.user.first_name %> <%= course.user.last_name %><br>
        <strong style="color: #003b46;">Mail ID: </strong><%= course.user.email%> 
    </p>
    </div>
    <%= button_to "Buy Now!", checkout_create_path, params: {id: course.id}, remote: true, style: 'background-color:#003b46; color: #ffffff; width: 100%;', class: "btn " %>
    </div>
    </div>
<% end %>
</div>
</ul>