EMentors/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main/index'
  root 'main#index'
  get 'students/dashboard/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  
  scope module: :teacher do
    resources :courses do
      resources :topics
    end
    resources :subscribers
  end
  
  scope module: :student do
    resources :dashboard 
    resources :purchases
    resources :subscriptions
    post "/checkout/create", to: "checkout#create"
    get '/checkout/success', to: "checkout#success"
    get '/checkout/cancel', to: "checkout#cancel"
    get 'payment/payment_successful', to: "payments#payment_successful"
    get 'payment/payment_cancel', to: "payments#payment_cancel"
  end
end

EMentors/app/controllers/teacher/base_controller.rb
module Teacher
    class BaseController < ::ApplicationController
        before_action :authenticate_user!, :is_teacher?
        layout 'teacher'
    end
end

EMentors/app/controllers/teacher/courses_controller.rb
module Teacher 
  class CoursesController < BaseController
      before_action :check_subscribed!, only: [:destroy]
      before_action :set_course, only: %i[show edit update destroy]
      def index
        @courses = current_user.courses.kept
      end
      
      def new
        @course = current_user.courses.new
      end
    
      def show;end
    
      def create
        @course = current_user.courses.new(course_params)
    
        if @course.save
          redirect_to course_path(@course)
        else 
          render :new
        end
      end
    
      def edit;end
    
      def update
        if @course.update(course_params)
          redirect_to @course
        else 
          render :edit
        end
      end
    
      def destroy
        if @course.discard
          redirect_to courses_path
        else
          redirect_to request.env["HTTP_REFERER"], notice: "Cannot perform action!"
        end
      end

      private

      def course_params
        params.require(:course).permit(:course_name, :course_description, :course_duration, :course_price)
      end

      def check_subscribed!
        if current_user.courses.find(params[:id]).purchases.count > 0
          return redirect_to request.env["HTTP_REFERER"], notice: "Cannot perform action!"
        end
      end

      def set_course
        @course = current_user.courses.find(params[:id])
      end
    end
  end

EMentors/app/controllers/teacher/subscribers_controller.rb
module Teacher
    class SubscribersController < BaseController
        def index
            @course = current_user.courses.find(params[:course_id])
            users_id = @course.purchases.pluck(:user_id)
            @users = User.where(id: users_id)
        end
    end
end

EMentors/app/controllers/teacher/topics_controller.rb
module Teacher
    class TopicsController < BaseController
        before_action :set_course, only: %i[new create edit update destroy]
        before_action :check_if_subscribed!, only: [:destroy]
        def new
            @topic = @course.topics.new
        end
        
        def create
            @topic = @course.topics.new(topics_params)
            if @topic.save
                redirect_to course_path(@course)
            else 
                render :new
            end
        end

        def edit
            @topic = @course.topics.find(params[:id])
        end

        def update
            @topic = @course.topics.find(params[:id])
            if @topic.update(topics_params)
                redirect_to course_path(@course)
            else 
                render :edit
            end
        end

        def destroy
            @topic = @course.topics.find(params[:id])
            if @topic.discard   
                respond_to do |format|
                    format.html { redirect_to course_path(@course) }
                    format.json { render :json => {:message => "success", :body => @topic} }
                end
            else
                respond_to do |format|
                    format.html { redirect_to request.env["HTTP_REFERER"], notice: "Cannot perform action!" }
                    format.json { render :json => {:message => "false"} }
                end 
            end
        end
        
        private

        def topics_params
            params.require(:topic).permit(:topic_name, :topic_description, :post_video)
        end
        
        def set_course
            @course = Course.find(params[:course_id])
        end

        def check_if_subscribed!
            if @course.purchases.count > 0
                return redirect_to request.env["HTTP_REFERER"], notice: "Cannot perform action!"
            end
        end
    end
end

EMentors/app/views/teacher/courses/_form.html.erb
<div class="d-flex align-items-center justify-content-center">
    <%= form_with model: course do |form|%>
        <div>
            <strong><%= form.label :course_name %> <br></strong>
            <%= form.text_field :course_name %> <br>
        </div>

        <div>
            <strong><%= form.label :course_description %> <br></strong>
            <%= form.text_field :course_description %> <br>
        </div>

        <div>
            <strong><%= form.label :course_duration %> <br></strong>
            <%= form.text_field :course_duration %> <br>
        </div>

        <div>
            <strong><%= form.label :course_price %> <br></strong>
            <%= form.number_field :course_price %> <br>
        </div>

        <div>
            <%= form.submit :Submit, {:style=>'width: 256px', :class => "btn btn-success"}%> <br>
        </div>
    <% end %>
</div>

EMentors/app/views/teacher/courses/edit.html.erb
<%# <h1 class="d-flex align-items-center justify-content-center">Edit your course</h1> %>
<%= render 'form', course: @course %>

EMentors/app/views/teacher/courses/index.html.erb
<div class="d-flex align-items-center justify-content-center" >
    <h1>Hello <%= current_user.first_name %>, Welcome to EMentors</h1>
</div>
<ul>
<%= link_to 'Create a new course', new_course_path,  class:"btn btn-success" %> 
<h3>List of all your courses:</h3>
<div class="row row-cols-1 row-cols-md-3 g-4" >
<% @courses.each do |course|%>
     <div class="col" style="width: 25%;">
    <div class="card" style="min-height: 100%;">
     <div class="card-body" style="background-color: #66A5AD  ; color: #c4dfe6;">
     <div ><h5 class="card-title" style="color: #003b46;"><%= course.course_name %> </h5></div>
     <p class="card-text"><strong>Description:</strong>
        <%= course.course_description %><br/>
        <strong>Duration: </strong><%= course.course_duration %><br>
        <strong>Price: </strong><%= course.course_price %></p>
    </p>
    </div>
    <%= link_to 'View Details', course_path(course.id), {:style=>'background-color:#003b46; color: #ffffff;', :class => "btn "} %> 
    </div>
    </div>
<% end %>
</div>
</ul>

EMentors/app/views/teacher/courses/new.html.erb
<%= render 'form', course: @course %>

EMentors/app/views/teacher/courses/show.html.erb
<%= link_to 'View Subscribers', subscribers_path(course_id: @course), class:"btn btn-success" %>
<%= link_to 'Create Topic', new_course_topic_path(@course), class:"btn btn-secondary"%><br><br>
<table class="table table-success table-striped">
    <thead>
        <tr>
            <th> Topic Name </th>
            <th> Topic Description </th>
            <th> Video Lecture</th>
            <th> Edit Link</th>
            <% if @course.purchases.count == 0 %>
                <th> Delete Link </th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @course.topics.kept.each do |topic| %>
            <tr>
                <td><%= topic.topic_name %> </td>
                <td><%= topic.topic_description %> </td>
                <% if topic.post_video.present? %>
                    <td><%= video_tag url_for(topic.post_video), controls: true, width: 200, height: 100 %> </td>
                <% end %>
                <td><%= link_to 'Edit Topic', edit_course_topic_path(course_id: @course, id: topic), class:"btn btn-info"%> 
                <% if @course.purchases.count == 0 %>
                    <td>  <button id="<%=topic.id%>", onclick="delete_topic(this)", class="btn btn-danger">Delete Topic</button> </td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<br>
<br>
<%= link_to 'Edit Course', edit_course_path(@course.id), class:"btn btn-info" %> 
<%= link_to 'Delete Course', course_path(@course.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

<script>
    function delete_topic(e) {
        var url = "/courses/" + <%=@course.id%> + "/topics/" + e.id
        $.ajax({
            url: url,
            method: 'delete',
            dataType: "json",
            success: function(data) {
                if (data.message == 'success') {
                    document.getElementById(data.body.id).parentElement.parentElement.remove()
                }
            }
        })
    }
</script>